// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20210223205021_referensremove")]
    partial class referensremove
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BaseMessageUser", b =>
                {
                    b.Property<Guid>("BaseMessageId")
                        .HasColumnType("uuid");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("BaseMessageId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("BaseMessageUser");
                });

            modelBuilder.Entity("DataAccessLayer.Model.BaseMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Loggin")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("BaseMessages");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "group1"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "group2"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "group3"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "group4"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "group5"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<Guid?>("BaseMessageId")
                        .HasColumnType("uuid");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Pass")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            GroupId = 1L,
                            Name = "User1",
                            Pass = "pass"
                        },
                        new
                        {
                            Id = 2L,
                            GroupId = 2L,
                            Name = "User2",
                            Pass = "pass"
                        },
                        new
                        {
                            Id = 3L,
                            GroupId = 3L,
                            Name = "User3",
                            Pass = "pass"
                        },
                        new
                        {
                            Id = 4L,
                            GroupId = 4L,
                            Name = "User4",
                            Pass = "pass"
                        },
                        new
                        {
                            Id = 5L,
                            GroupId = 5L,
                            Name = "User5",
                            Pass = "pass"
                        });
                });

            modelBuilder.Entity("BaseMessageUser", b =>
                {
                    b.HasOne("DataAccessLayer.Model.BaseMessage", null)
                        .WithMany()
                        .HasForeignKey("BaseMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Model.BaseMessage", b =>
                {
                    b.HasOne("DataAccessLayer.Model.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DataAccessLayer.Model.User", b =>
                {
                    b.HasOne("DataAccessLayer.Model.Group", "Group")
                        .WithMany("User")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DataAccessLayer.Model.Group", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
